#
# Noel Rafferty
#
# As COMPUTER SCIENCE

def three():
    try:
        pass
    except Exception as e:
        print("Error Occurred:", e)

def two():
    try:
        pass
    except Exception as e:
        print("Error Occurred:", e)

def one():
    try:
        pass
    except Exception as e:
        print("Error Occurred:", e)

def main():
    try:
        three()
        two()
        one()
    except Exception as e:
        print("Error Occurred:", e)

if __name__ == "__main__":
    main()


